###########################################################
# Makefile generated by xIDE                               
#                                                          
# Project: I2C
# Configuration: Release
# Generated: 周二 五月 1 09:13:01 2018
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

OUTPUT=I2C
OUTDIR=D:/Dev/projects/optogenetics/CSR8670/I2C
HARDWARE_INDEX=1
DEFS=

DEBUGTRANSPORT=SPITRANS=USB SPIPORT=0
EXECUTION_MODE=hw_default
STACKSIZE=0
TRANSPORT=bcsp
FIRMWARE=unified
FIRMWAREIMAGE=
LIBRARY_VERSION=
GENERATE_MAP=1

INPUTS=main.c

-include I2C.mak
include $(BLUELAB)/Makefile.vm
